name: dashboard
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0





dependencies:
  flutter:
    sdk: flutter


  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8 

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0

  # State Management
  get: ^4.7.2
  get_storage: ^2.1.1

  # Web Specific
  web: ^1.1.1
  http: ^1.4.0
  html: ^0.15.6
  fl_chart: ^0.68.0
  data_table_2: ^2.6.0
  url_strategy: ^0.3.0
  universal_html: ^2.2.4

  # images
  flutter_svg: ^2.2.0

  # SupaBase  
  supabase_flutter: ^2.9.1
  
  # Utility Packages
  intl: ^0.20.2
  lottie: ^3.3.1
  shimmer: ^3.0.0
  clipboard: ^0.1.3
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  flutter_dropzone: ^4.2.1
  connectivity_plus: ^6.1.4
  multi_select_flutter: ^4.1.3
  cached_network_image: ^3.4.1
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1

  # Unditected
  html_editor_enhanced: ^2.7.1
  firebase_storage: ^13.0.0
  path_provider: ^2.1.5

  #YouTube Uploader


#  file_picker: ^6.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true


  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/images/
    - assets/logos/
    - assets/images/content/
    - assets/images/animations/
    - assets/icons/payment_methods/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/urbanist/Urbanist-Italic.ttf
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/urbanist/Urbanist-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/urbanist/Urbanist-Bold.ttf
          weight: 800